# -*- coding: utf-8 -*-
"""TWSMA-Experiment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NAQSAKwxU9_1eh_GVBb7ZEs1xjqAuoyf
"""

# STEP 1: INSTALL REQUIRED LIBRARIES

!pip install -q gensim pyLDAvis wordcloud

print("Required packages installed successfully!")

# STEP 1B: IMPORT LIBRARIES

import pandas as pd
import numpy as np
import nltk
import spacy
import gensim
import matplotlib.pyplot as plt

from collections import Counter
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

print("Libraries imported successfully!")
print("Gensim version:", gensim.__version__)

# STEP 1C: DOWNLOAD SPACY ENGLISH MODEL

!python -m spacy download en_core_web_sm

# STEP 2: CREATE NEWS ARTICLE DATASET

data = {
    "Article_ID": list(range(1, 25)),

    "Title": [
        "OpenAI Launches New Artificial Intelligence Model",
        "Google Expands AI Research and Cloud Services",
        "Microsoft Invests in Advanced AI Technology",
        "Apple Develops New Artificial Intelligence Features",
        "Amazon Uses AI to Improve Online Shopping",
        "Nvidia Announces New Chips for AI Systems",

        "Tesla Reports Strong Growth in Electric Vehicle Sales",
        "Microsoft Reports Higher Quarterly Revenue",
        "Amazon Expands Business Operations Across Europe",
        "Apple Reports Strong iPhone Sales",
        "Google Cloud Revenue Continues to Increase",
        "Samsung Announces Major Investment in Technology",

        "India Wins Cricket Series Against Australia",
        "Virat Kohli Leads India to Victory",
        "England Prepares for Major Cricket Tournament",
        "Real Madrid Wins Important Football Match",
        "Olympic Athletes Begin Training for Paris Games",
        "Manchester City Announces New Football Strategy",

        "Scientists Report Rising Global Temperatures",
        "India Announces New Renewable Energy Projects",
        "United Nations Discusses Climate Change Action",
        "European Countries Increase Solar Energy Capacity",
        "Scientists Study Melting Antarctic Ice",
        "Government Launches New Environmental Protection Program"
    ],

    "Article": [
        "OpenAI announced a new artificial intelligence model designed to improve language understanding and automated reasoning. CEO Sam Altman said the technology will support businesses and researchers around the world.",

        "Google expanded its artificial intelligence research and cloud computing services. CEO Sundar Pichai said new AI tools will help companies analyze data and develop digital products.",

        "Microsoft announced a major investment in artificial intelligence technology and cloud infrastructure. CEO Satya Nadella said the company will continue developing AI services for businesses.",

        "Apple is developing new artificial intelligence features for its devices and software. CEO Tim Cook said the company is focusing on privacy, performance and personalized digital services.",

        "Amazon is using artificial intelligence to improve online shopping and logistics. CEO Andy Jassy said machine learning can help customers discover products and improve delivery operations.",

        "Nvidia announced new computer chips designed for artificial intelligence systems. CEO Jensen Huang said demand for AI computing infrastructure continues to grow among technology companies.",

        "Tesla reported strong growth in electric vehicle sales during the latest quarter. CEO Elon Musk said the company plans to expand production and improve battery technology.",

        "Microsoft reported higher quarterly revenue as demand for cloud computing and software services increased. Satya Nadella said business customers are adopting artificial intelligence tools rapidly.",

        "Amazon announced plans to expand its business operations across Europe. Andy Jassy said the company will increase investment in logistics, cloud services and digital commerce.",

        "Apple reported strong iPhone sales and higher quarterly revenue. Tim Cook said demand for premium smartphones and digital services remained strong in international markets.",

        "Google reported continued growth in cloud computing revenue. Sundar Pichai said enterprise customers are increasing spending on cloud infrastructure and artificial intelligence services.",

        "Samsung announced a major investment in technology manufacturing and semiconductor production. The company said the investment will strengthen its global supply chain and business operations.",

        "India won a cricket series against Australia after strong performances from its batting and bowling teams. Captain Rohit Sharma praised the players for their teamwork and discipline.",

        "Virat Kohli led India to an important cricket victory with an outstanding batting performance. The match attracted thousands of supporters and generated significant media attention.",

        "England began preparations for a major international cricket tournament. Coach Brendon McCullum said the team is focused on fitness, strategy and consistent performances.",

        "Real Madrid won an important football match after scoring two goals in the second half. Manager Carlo Ancelotti praised the team's defensive performance and tactical discipline.",

        "Olympic athletes have begun intensive training ahead of the upcoming Games. Indian athlete Neeraj Chopra said preparation, fitness and mental strength are essential for success.",

        "Manchester City announced a new football strategy focused on developing young players and improving team performance. Manager Pep Guardiola said the club will continue investing in training.",

        "Scientists reported that global temperatures continue to rise as greenhouse gas emissions remain high. Researchers said governments must accelerate climate action to reduce environmental risks.",

        "India announced new renewable energy projects involving solar and wind power. Energy Minister R K Singh said the projects will increase clean energy production and reduce dependence on fossil fuels.",

        "The United Nations held discussions on climate change and global environmental policy. Secretary-General António Guterres urged countries to increase cooperation and reduce carbon emissions.",

        "European countries announced plans to increase solar energy capacity. Officials said renewable energy investments can improve energy security while reducing carbon emissions.",

        "Scientists are studying the rapid melting of Antarctic ice and its potential effect on sea levels. Researchers said continued monitoring is necessary to understand long-term climate risks.",

        "The government launched a new environmental protection program focused on forests, clean water and pollution reduction. Environment Minister Bhupender Yadav said the program will support sustainable development."
    ]
}

df = pd.DataFrame(data)

print("News Dataset Created Successfully!")
print("Number of articles:", len(df))

display(df[["Article_ID", "Title", "Article"]])

# STEP 3: EXPLORE THE DATASET

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nFirst 5 Articles:")
display(df.head())

# STEP 4: NAMED ENTITY RECOGNITION USING SPACY

import spacy

# Load English spaCy model
nlp = spacy.load("en_core_web_sm")

# Function to extract selected entities
def extract_entities(text):
    doc = nlp(text)

    entities = []

    for ent in doc.ents:
        if ent.label_ in ["PERSON", "ORG", "GPE", "DATE"]:
            entities.append({
                "Entity": ent.text,
                "Label": ent.label_
            })

    return entities

# Apply NER
df["Named_Entities"] = df["Article"].apply(extract_entities)

print("Named Entity Recognition Results:")
display(df[["Article_ID", "Title", "Named_Entities"]])

# STEP 5: CREATE STRUCTURED ENTITY TABLE

entity_rows = []

for _, row in df.iterrows():

    for entity in row["Named_Entities"]:

        entity_rows.append({
            "Article_ID": row["Article_ID"],
            "Title": row["Title"],
            "Entity": entity["Entity"],
            "Entity_Type": entity["Label"]
        })

entity_df = pd.DataFrame(entity_rows)

print("Structured Named Entity Table:")
display(entity_df)

# STEP 6: TEXT CLEANING AND TOKENIZATION

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def clean_text(text):

    # Convert to lowercase
    text = text.lower()

    # Tokenize
    tokens = word_tokenize(text)

    # Remove stop words, punctuation and non-alphabetic tokens
    tokens = [
        word for word in tokens
        if word.isalpha() and word not in stop_words
    ]

    # Lemmatization
    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    return tokens

df["Cleaned_Tokens"] = df["Article"].apply(clean_text)

print("Cleaned and Lemmatized Text:")
display(df[["Title", "Cleaned_Tokens"]])

# STEP 7: CREATE CLEANED TEXT COLUMN

df["Cleaned_Text"] = df["Cleaned_Tokens"].apply(
    lambda tokens: " ".join(tokens)
)

print("Original vs Cleaned Text:")
display(df[["Title", "Article", "Cleaned_Text"]])

# STEP 8: CREATE GENSIM DICTIONARY

from gensim import corpora

# Create dictionary
dictionary = corpora.Dictionary(df["Cleaned_Tokens"])

print("Number of unique terms:", len(dictionary))

print("\nSample Dictionary:")
print(list(dictionary.token2id.items())[:20])

# STEP 9: CREATE GENSIM CORPUS

# Convert documents into Bag-of-Words representation
corpus = [
    dictionary.doc2bow(tokens)
    for tokens in df["Cleaned_Tokens"]
]

print("Number of documents:", len(corpus))

print("\nFirst Document - Bag of Words:")
print(corpus[0])

# STEP 10: LATENT DIRICHLET ALLOCATION (LDA)

from gensim.models import LdaModel

NUM_TOPICS = 4

lda_model = LdaModel(
    corpus=corpus,
    id2word=dictionary,
    num_topics=NUM_TOPICS,
    random_state=42,
    passes=15,
    alpha="auto",
    per_word_topics=True
)

print("LDA model created successfully!")
print("Number of topics:", NUM_TOPICS)

# STEP 11: DISPLAY TOP WORDS FOR EACH TOPIC

print("DOMINANT TOPICS")
print("=" * 60)

for topic_id, words in lda_model.show_topics(
    num_topics=NUM_TOPICS,
    num_words=10,
    formatted=False
):

    print(f"\nTopic {topic_id + 1}:")

    for word, probability in words:
        print(f"{word}: {probability:.4f}")

# STEP 12: CREATE TOPIC KEYWORD TABLE

topic_rows = []

for topic_id in range(NUM_TOPICS):

    words = lda_model.show_topic(
        topic_id,
        topn=10
    )

    keywords = ", ".join(
        [word for word, probability in words]
    )

    topic_rows.append({
        "Topic": f"Topic {topic_id + 1}",
        "Top_Keywords": keywords
    })

topic_df = pd.DataFrame(topic_rows)

print("Topic Keywords:")
display(topic_df)

# STEP 13: ASSIGN DOMINANT TOPIC TO EACH ARTICLE

def get_dominant_topic(bow):

    topic_distribution = lda_model.get_document_topics(
        bow,
        minimum_probability=0
    )

    dominant_topic = max(
        topic_distribution,
        key=lambda x: x[1]
    )

    return dominant_topic[0], dominant_topic[1]

dominant_topics = []

for bow in corpus:

    topic_id, probability = get_dominant_topic(bow)

    dominant_topics.append(topic_id)

df["Dominant_Topic"] = [
    topic + 1
    for topic in dominant_topics
]

df["Topic_Probability"] = [
    get_dominant_topic(bow)[1]
    for bow in corpus
]

print("Articles with Dominant Topics:")
display(
    df[
        [
            "Article_ID",
            "Title",
            "Dominant_Topic",
            "Topic_Probability"
        ]
    ]
)

# STEP 14: MAP TOPICS TO HUMAN-READABLE NAMES
#
# IMPORTANT:
# Check Cell 12 before running this cell.
# If your topic numbers correspond differently, change the names below.

topic_names = {
    1: "Technology and Artificial Intelligence",
    2: "Business and Companies",
    3: "Sports",
    4: "Climate and Environment"
}

df["Topic_Name"] = df["Dominant_Topic"].map(topic_names)

print("Articles with Topic Names:")
display(
    df[
        [
            "Article_ID",
            "Title",
            "Dominant_Topic",
            "Topic_Name"
        ]
    ]
)

# STEP 15: ADD TOPIC KEYWORDS TO EACH ARTICLE

topic_keywords = {}

for topic_id in range(NUM_TOPICS):

    words = lda_model.show_topic(
        topic_id,
        topn=10
    )

    topic_keywords[topic_id + 1] = ", ".join(
        [word for word, probability in words]
    )

df["Topic_Keywords"] = df["Dominant_Topic"].map(
    topic_keywords
)

print("Article Topic Mapping:")
display(
    df[
        [
            "Article_ID",
            "Title",
            "Topic_Name",
            "Topic_Keywords"
        ]
    ]
)

# STEP 16: INTEGRATE NAMED ENTITIES WITH TOPICS

integration_df = df[
    [
        "Article_ID",
        "Title",
        "Named_Entities",
        "Dominant_Topic",
        "Topic_Name",
        "Topic_Keywords"
    ]
].copy()

print("NER + Topic Modelling Integration:")
display(integration_df)

# STEP 17: MAP ENTITIES TO TOPICS

entity_topic_rows = []

for _, row in df.iterrows():

    for entity in row["Named_Entities"]:

        entity_topic_rows.append({
            "Article_ID": row["Article_ID"],
            "Entity": entity["Entity"],
            "Entity_Type": entity["Label"],
            "Topic": row["Topic_Name"]
        })

entity_topic_df = pd.DataFrame(entity_topic_rows)

print("Entity-to-Topic Mapping:")
display(entity_topic_df)

# STEP 18: VISUALIZE TOPIC DISTRIBUTION

topic_counts = df["Topic_Name"].value_counts()

plt.figure(figsize=(10, 6))

plt.bar(
    topic_counts.index,
    topic_counts.values
)

plt.title("Distribution of Articles Across Topics")
plt.xlabel("Topic")
plt.ylabel("Number of Articles")
plt.xticks(rotation=30, ha="right")

plt.tight_layout()
plt.show()

# STEP 19: VISUALIZE DOMINANT TOPIC PROBABILITIES

plt.figure(figsize=(10, 6))

plt.bar(
    df["Article_ID"],
    df["Topic_Probability"]
)

plt.title("Dominant Topic Probability by Article")
plt.xlabel("Article ID")
plt.ylabel("Topic Probability")

plt.tight_layout()
plt.show()

# STEP 20: GENERATE WORD CLOUDS FOR TOPICS

from wordcloud import WordCloud

for topic_id in range(NUM_TOPICS):

    words = lda_model.show_topic(
        topic_id,
        topn=20
    )

    word_frequency = {
        word: probability
        for word, probability in words
    }

    wordcloud = WordCloud(
        width=900,
        height=500,
        background_color="white"
    ).generate_from_frequencies(word_frequency)

    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation="bilinear")
    plt.axis("off")
    plt.title(
        f"Topic {topic_id + 1}: "
        f"{topic_names.get(topic_id + 1, 'Topic')}"
    )

    plt.show()

# STEP 21: OPTIONAL pyLDAvis VISUALIZATION

import pyLDAvis
import pyLDAvis.gensim_models as gensimvis

# Prepare visualization
lda_vis = gensimvis.prepare(
    lda_model,
    corpus,
    dictionary
)

pyLDAvis.display(lda_vis)

# STEP 22: CREATE FINAL TOPIC SUMMARY

topic_summary = []

for topic_id in range(1, NUM_TOPICS + 1):

    article_count = (
        df["Dominant_Topic"] == topic_id
    ).sum()

    topic_summary.append({
        "Topic": f"Topic {topic_id}",
        "Topic_Name": topic_names.get(
            topic_id,
            f"Topic {topic_id}"
        ),
        "Top_Keywords": topic_keywords[topic_id],
        "Number_of_Articles": article_count
    })

topic_summary_df = pd.DataFrame(topic_summary)

print("FINAL TOPIC SUMMARY")
display(topic_summary_df)

# STEP 23: CREATE LAYMAN'S TOPIC EXPLANATIONS

topic_explanations = {
    "Technology and Artificial Intelligence":
        "Articles discussing artificial intelligence, software, cloud computing, digital services and technology companies.",

    "Business and Companies":
        "Articles discussing company revenue, investments, sales, expansion and business operations.",

    "Sports":
        "Articles discussing cricket, football, athletes, matches, teams and sporting events.",

    "Climate and Environment":
        "Articles discussing climate change, renewable energy, global temperatures, pollution and environmental protection."
}

topic_summary_df["Layman_Explanation"] = (
    topic_summary_df["Topic_Name"].map(topic_explanations)
)

print("Topic Summary in Simple Language:")
display(topic_summary_df)

# STEP 24: CREATE FINAL OUTPUT TABLE

final_df = df[
    [
        "Article_ID",
        "Title",
        "Article",
        "Cleaned_Text",
        "Named_Entities",
        "Dominant_Topic",
        "Topic_Name",
        "Topic_Keywords",
        "Topic_Probability"
    ]
].copy()

print("FINAL EXPERIMENT OUTPUT:")
display(final_df)

# STEP 25: SAVE FINAL CSV

# Convert entity lists into readable text
final_df["Named_Entities"] = final_df["Named_Entities"].apply(
    lambda entities: " | ".join(
        f"{e['Entity']} ({e['Label']})"
        for e in entities
    )
)

final_df.to_csv(
    "Experiment_2_Final_Output.csv",
    index=False
)

print("Final CSV created successfully!")
print("File name: Experiment_2_Final_Output.csv")
print("Rows:", len(final_df))
print("Columns:", len(final_df.columns))

display(final_df)

# STEP 26: SAVE NER OUTPUT

entity_df.to_csv(
    "Experiment_2_NER_Output.csv",
    index=False
)

print("NER CSV created successfully!")
print("File name: Experiment_2_NER_Output.csv")

display(entity_df)

# STEP 27: SAVE TOPIC SUMMARY

topic_summary_df.to_csv(
    "Experiment_2_Topic_Summary.csv",
    index=False
)

print("Topic Summary CSV created successfully!")
print("File name: Experiment_2_Topic_Summary.csv")

display(topic_summary_df)

# STEP 28: DOWNLOAD OUTPUT FILES

from google.colab import files

print("Output files ready:")
print("1. Experiment_2_Final_Output.csv")
print("2. Experiment_2_NER_Output.csv")
print("3. Experiment_2_Topic_Summary.csv")

# Download final main output
files.download("Experiment_2_Final_Output.csv")
