# -*- coding: utf-8 -*-
"""TWSMA-Experiment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMRXlbna7jjiMsdzLSheFvDTChbmlhRR
"""

# CELL 1: IMPORT LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

from wordcloud import WordCloud

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

print("Libraries imported successfully!")

# CELL 2: CREATE CUSTOMER FEEDBACK DATASET

delivery = [
    "My order arrived very late.",
    "Delivery was delayed by two days.",
    "Package reached after expected date.",
    "Late delivery disappointed me.",
    "Delivery tracking was inaccurate."
]

support = [
    "Customer support was very helpful.",
    "Support team solved my issue quickly.",
    "Customer care was unresponsive.",
    "Long waiting time for support.",
    "Support executive behaved politely."
]

quality = [
    "Product quality is excellent.",
    "The item was damaged.",
    "Received poor quality product.",
    "Packaging was damaged.",
    "Very satisfied with product quality."
]

payment = [
    "Refund process was slow.",
    "Payment failed during checkout.",
    "Money was deducted twice.",
    "Refund was credited quickly.",
    "Easy payment experience."
]

positive = [
    "Amazing shopping experience.",
    "Very happy with the service.",
    "Fast delivery and good quality.",
    "Excellent customer experience.",
    "Highly recommend this service."
]

feedback = []

for i in range(24):
    feedback.extend([
        random.choice(delivery),
        random.choice(support),
        random.choice(quality),
        random.choice(payment),
        random.choice(positive)
    ])

df = pd.DataFrame({"Feedback": feedback})

print("Total Feedback Entries:", len(df))
display(df.head())

# CELL 3: DATASET EXPLORATION

print("Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nSample Feedback:")
display(df.sample(10))

# CELL 4: TEXT PREPROCESSING

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess(text):

    text = text.lower()

    tokens = word_tokenize(text)

    tokens = [
        word for word in tokens
        if word.isalpha() and word not in stop_words
    ]

    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    return " ".join(tokens)

df["Cleaned_Feedback"] = df["Feedback"].apply(preprocess)

display(df.head())

# CELL 5: TF-IDF FEATURE EXTRACTION

vectorizer = TfidfVectorizer(max_features=500)

X = vectorizer.fit_transform(df["Cleaned_Feedback"])

print("TF-IDF Matrix Shape:", X.shape)

# CELL 6: ELBOW METHOD

wcss = []

for i in range(2, 8):

    kmeans = KMeans(
        n_clusters=i,
        random_state=42,
        n_init=10
    )

    kmeans.fit(X)

    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8,5))

plt.plot(range(2,8), wcss, marker="o")

plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")

plt.show()

# CELL 7: APPLY K-MEANS

kmeans = KMeans(
    n_clusters=5,
    random_state=42,
    n_init=10
)

df["Cluster"] = kmeans.fit_predict(X)

print("Cluster Distribution:")
print(df["Cluster"].value_counts())

display(df.head())

# CELL 8: CLUSTER-WISE FEEDBACK

for cluster in sorted(df["Cluster"].unique()):

    print("="*50)
    print("CLUSTER", cluster)

    sample = df[df["Cluster"]==cluster]["Feedback"].head(5)

    for item in sample:
        print("-", item)

    print()

# CELL 9: WORD CLOUD FOR EACH CLUSTER

for cluster in sorted(df["Cluster"].unique()):

    text = " ".join(
        df[df["Cluster"]==cluster]["Cleaned_Feedback"]
    )

    wc = WordCloud(
        width=800,
        height=400,
        background_color="white"
    ).generate(text)

    plt.figure(figsize=(8,4))
    plt.imshow(wc, interpolation="bilinear")
    plt.axis("off")
    plt.title(f"Cluster {cluster}")
    plt.show()

# CELL 10: LABEL CLUSTERS AND SAVE OUTPUT

cluster_labels = {
    0: "Delivery Delay",
    1: "Customer Support",
    2: "Product Quality",
    3: "Payment & Refund",
    4: "Positive Feedback"
}

df["Theme"] = df["Cluster"].map(cluster_labels)

print("Cluster-wise Theme Summary")
display(df[["Feedback","Cluster","Theme"]].head(20))

summary = df.groupby("Theme").size().reset_index(name="Feedback_Count")

print("\nTheme Summary")
display(summary)

df.to_csv("Experiment_4_Clustered_Feedback.csv", index=False)

print("CSV Saved Successfully!")
