# -*- coding: utf-8 -*-
"""TWSMA-Experiment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADv8zoMnUqc1nsbT0BMlutQL_Ya6QX0X
"""

# CELL 1: IMPORT LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

print("Libraries imported successfully!")

# CELL 2: LOAD NEWS AGGREGATOR DATASET

import os

# Check possible file locations
possible_paths = [
    "/newsCorpora.csv",
    "/content/newsCorpora.csv"
]

file_path = None

for path in possible_paths:
    if os.path.exists(path):
        file_path = path
        break

if file_path is None:
    raise FileNotFoundError(
        "newsCorpora.csv was not found. Please upload the file again."
    )

print("File found at:", file_path)

columns = [
    "ID",
    "TITLE",
    "URL",
    "PUBLISHER",
    "CATEGORY",
    "STORY",
    "HOSTNAME",
    "TIMESTAMP"
]

df = pd.read_csv(
    file_path,
    sep="\t",
    names=columns
)

print("\nTotal News Articles:", len(df))
print("Dataset Shape:", df.shape)

display(df.head())

# CELL 3: SELECT 1000 REAL NEWS ARTICLES

# Remove missing headlines
df = df.dropna(subset=["TITLE"])

# Sample 1000 articles
df_sample = df.sample(
    n=1000,
    random_state=42
).reset_index(drop=True)

print("Selected Articles:", len(df_sample))

print("\nCategory Distribution:")
print(df_sample["CATEGORY"].value_counts())

display(
    df_sample[
        ["TITLE", "PUBLISHER", "CATEGORY"]
    ].head(10)
)

# CELL 4: TEXT PREPROCESSING

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):

    text = text.lower()

    tokens = word_tokenize(text)

    tokens = [
        word for word in tokens
        if word.isalpha()
        and word not in stop_words
    ]

    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    return " ".join(tokens)


df_sample["Cleaned_Title"] = (
    df_sample["TITLE"]
    .apply(preprocess_text)
)

display(
    df_sample[
        ["TITLE", "Cleaned_Title"]
    ].head(10)
)

# CELL 5: BAG OF WORDS AND TF-IDF

# Bag of Words
bow_vectorizer = CountVectorizer(
    max_features=5000
)

bow_matrix = bow_vectorizer.fit_transform(
    df_sample["Cleaned_Title"]
)

print("Bag of Words Shape:",
      bow_matrix.shape)


# TF-IDF
tfidf_vectorizer = TfidfVectorizer(
    max_features=5000
)

tfidf_matrix = tfidf_vectorizer.fit_transform(
    df_sample["Cleaned_Title"]
)

print("TF-IDF Shape:",
      tfidf_matrix.shape)

# CELL 6: USER QUERY

query = input(
    "Enter your news search query: "
)

cleaned_query = preprocess_text(query)

print("\nOriginal Query:")
print(query)

print("\nProcessed Query:")
print(cleaned_query)

# CELL 7: COSINE SIMILARITY

query_vector = tfidf_vectorizer.transform(
    [cleaned_query]
)

similarity_scores = cosine_similarity(
    query_vector,
    tfidf_matrix
).flatten()

df_sample["Similarity_Score"] = (
    similarity_scores
)

print("Cosine similarity calculated successfully!")

# CELL 8: RANK SEARCH RESULTS

results = df_sample.sort_values(
    by="Similarity_Score",
    ascending=False
)

top_5 = results.head(5)

print("\nTOP 5 MOST RELEVANT NEWS ARTICLES")
print("=" * 70)

for i, (_, row) in enumerate(
    top_5.iterrows(), start=1
):

    print(f"\nRank {i}")
    print("-" * 70)

    print("Headline:", row["TITLE"])
    print("Publisher:", row["PUBLISHER"])
    print("Category:", row["CATEGORY"])
    print(
        "Similarity Score:",
        round(row["Similarity_Score"], 4)
    )
    print("URL:", row["URL"])

# CELL 9: VISUALIZE TOP 5 RESULTS

plot_data = top_5.sort_values(
    "Similarity_Score",
    ascending=True
)

labels = [
    f"Article {i}"
    for i in plot_data["ID"]
]

plt.figure(figsize=(9, 5))

plt.barh(
    labels,
    plot_data["Similarity_Score"]
)

plt.xlabel("Cosine Similarity Score")
plt.ylabel("News Article")
plt.title("Top 5 Relevant News Articles")

plt.tight_layout()
plt.show()

# CELL 10: SAVE SEARCH RESULTS

search_results = top_5[
    [
        "TITLE",
        "PUBLISHER",
        "CATEGORY",
        "URL",
        "Similarity_Score"
    ]
].copy()

search_results.to_csv(
    "Experiment_5_Search_Results.csv",
    index=False
)

print("Search results saved successfully!")

display(
    search_results.round(4)
)