# -*- coding: utf-8 -*-
"""TWSMA-Experiment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcaAj01dtqeWSJ2xwkVZ48TFX_GPGLMk
"""

# CELL 1: IMPORT LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

print("Libraries imported successfully!")

# CELL 2: LOAD NEWS DATASET

categories = [
    "rec.sport.baseball",
    "sci.space",
    "talk.politics.misc",
    "rec.autos"
]

train_data = fetch_20newsgroups(
    subset="train",
    categories=categories,
    remove=("headers", "footers", "quotes")
)

test_data = fetch_20newsgroups(
    subset="test",
    categories=categories,
    remove=("headers", "footers", "quotes")
)

train_df = pd.DataFrame({
    "Article": train_data.data,
    "Category": [
        train_data.target_names[i]
        for i in train_data.target
    ]
})

test_df = pd.DataFrame({
    "Article": test_data.data,
    "Category": [
        test_data.target_names[i]
        for i in test_data.target
    ]
})

print("Training Articles:", len(train_df))
print("Testing Articles:", len(test_df))

print("\nCategories:")
print(train_data.target_names)

display(train_df.head())

# CELL 3: DATASET EXPLORATION

print("Training Dataset Shape:", train_df.shape)
print("Testing Dataset Shape:", test_df.shape)

print("\nCategory Distribution:")
print(train_df["Category"].value_counts())

print("\nMissing Values:")
print(train_df.isnull().sum())

# Visualization
category_counts = train_df["Category"].value_counts()

plt.figure(figsize=(9, 5))
plt.bar(
    category_counts.index,
    category_counts.values
)

plt.title("News Category Distribution")
plt.xlabel("Category")
plt.ylabel("Number of Articles")

plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.show()

# CELL 4: TEXT PREPROCESSING

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):

    # Lowercase
    text = text.lower()

    # Tokenization
    tokens = word_tokenize(text)

    # Remove stopwords, punctuation and numbers
    tokens = [
        word for word in tokens
        if word.isalpha()
        and word not in stop_words
    ]

    # Lemmatization
    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    return " ".join(tokens)


train_df["Cleaned_Text"] = train_df[
    "Article"
].apply(preprocess_text)

test_df["Cleaned_Text"] = test_df[
    "Article"
].apply(preprocess_text)

print("Text preprocessing completed!")

display(
    train_df[
        ["Article", "Cleaned_Text", "Category"]
    ].head()
)

# CELL 5: BAG OF WORDS AND TF-IDF

X_train_text = train_df["Cleaned_Text"]
y_train = train_df["Category"]

X_test_text = test_df["Cleaned_Text"]
y_test = test_df["Category"]

# Bag of Words
bow_vectorizer = CountVectorizer(
    max_features=5000
)

X_train_bow = bow_vectorizer.fit_transform(
    X_train_text
)

X_test_bow = bow_vectorizer.transform(
    X_test_text
)

# TF-IDF
tfidf_vectorizer = TfidfVectorizer(
    max_features=5000
)

X_train_tfidf = tfidf_vectorizer.fit_transform(
    X_train_text
)

X_test_tfidf = tfidf_vectorizer.transform(
    X_test_text
)

print("Bag of Words Shape:")
print("Training:", X_train_bow.shape)
print("Testing :", X_test_bow.shape)

print("\nTF-IDF Shape:")
print("Training:", X_train_tfidf.shape)
print("Testing :", X_test_tfidf.shape)

# CELL 6: TRAIN NAÏVE BAYES AND LOGISTIC REGRESSION

# Naïve Bayes
nb_model = MultinomialNB()

nb_model.fit(
    X_train_tfidf,
    y_train
)

nb_predictions = nb_model.predict(
    X_test_tfidf
)


# Logistic Regression
lr_model = LogisticRegression(
    max_iter=1000
)

lr_model.fit(
    X_train_tfidf,
    y_train
)

lr_predictions = lr_model.predict(
    X_test_tfidf
)

print("Both classifiers trained successfully!")

# CELL 7: MODEL EVALUATION

def evaluate_model(name, y_true, y_pred):

    accuracy = accuracy_score(
        y_true,
        y_pred
    )

    precision = precision_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    print("\n" + "=" * 50)
    print(name)
    print("=" * 50)

    print(f"Accuracy  : {accuracy:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1 Score  : {f1:.4f}")

    print("\nClassification Report:")
    print(
        classification_report(
            y_true,
            y_pred,
            zero_division=0
        )
    )

    return accuracy, precision, recall, f1


nb_scores = evaluate_model(
    "NAÏVE BAYES",
    y_test,
    nb_predictions
)

lr_scores = evaluate_model(
    "LOGISTIC REGRESSION",
    y_test,
    lr_predictions
)

# CELL 8: CONFUSION MATRICES

labels = train_data.target_names

# Naïve Bayes
nb_cm = confusion_matrix(
    y_test,
    nb_predictions,
    labels=labels
)

# Logistic Regression
lr_cm = confusion_matrix(
    y_test,
    lr_predictions,
    labels=labels
)

print("Naïve Bayes Confusion Matrix:")
print(nb_cm)

print("\nLogistic Regression Confusion Matrix:")
print(lr_cm)


# Display Naïve Bayes
disp1 = ConfusionMatrixDisplay(
    confusion_matrix=nb_cm,
    display_labels=labels
)

fig, ax = plt.subplots(figsize=(8, 6))
disp1.plot(ax=ax, xticks_rotation=45)
plt.title("Naïve Bayes Confusion Matrix")
plt.tight_layout()
plt.show()


# Display Logistic Regression
disp2 = ConfusionMatrixDisplay(
    confusion_matrix=lr_cm,
    display_labels=labels
)

fig, ax = plt.subplots(figsize=(8, 6))
disp2.plot(ax=ax, xticks_rotation=45)
plt.title("Logistic Regression Confusion Matrix")
plt.tight_layout()
plt.show()

# CELL 9: MODEL COMPARISON AND CATEGORY-WISE ANALYSIS

comparison_df = pd.DataFrame({

    "Model": [
        "Naïve Bayes",
        "Logistic Regression"
    ],

    "Accuracy": [
        nb_scores[0],
        lr_scores[0]
    ],

    "Precision": [
        nb_scores[1],
        lr_scores[1]
    ],

    "Recall": [
        nb_scores[2],
        lr_scores[2]
    ],

    "F1 Score": [
        nb_scores[3],
        lr_scores[3]
    ]
})

print("MODEL COMPARISON")
display(
    comparison_df.round(4)
)


# Category-wise performance for Logistic Regression
from sklearn.metrics import precision_recall_fscore_support

precision, recall, f1, support = (
    precision_recall_fscore_support(
        y_test,
        lr_predictions,
        labels=labels,
        zero_division=0
    )
)

category_df = pd.DataFrame({

    "Category": labels,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "Support": support
})

print("\nCATEGORY-WISE PERFORMANCE")
display(
    category_df.round(4)
)


# Comparison graph
metrics = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1 Score"
]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(9, 5))

plt.bar(
    x - width/2,
    comparison_df.iloc[0][metrics],
    width,
    label="Naïve Bayes"
)

plt.bar(
    x + width/2,
    comparison_df.iloc[1][metrics],
    width,
    label="Logistic Regression"
)

plt.xticks(x, metrics)
plt.ylim(0, 1.05)

plt.xlabel("Evaluation Metric")
plt.ylabel("Score")

plt.title("Classifier Performance Comparison")

plt.legend()
plt.tight_layout()
plt.show()

# CELL 10: MISCLASSIFICATION ANALYSIS AND FINAL OUTPUT

results_df = test_df[
    ["Article", "Category"]
].copy()

results_df["Predicted_Category"] = (
    lr_predictions
)

results_df["Correct"] = (
    results_df["Category"]
    ==
    results_df["Predicted_Category"]
)

# Misclassified articles
misclassified_df = results_df[
    results_df["Correct"] == False
]

print(
    "Total Test Articles:",
    len(results_df)
)

print(
    "Correctly Classified:",
    results_df["Correct"].sum()
)

print(
    "Misclassified:",
    len(misclassified_df)
)

print("\nMISCLASSIFIED ARTICLES:")
display(
    misclassified_df[
        [
            "Article",
            "Category",
            "Predicted_Category"
        ]
    ].head(10)
)


# Save final output
results_df.to_csv(
    "Experiment_3_Final_Classification.csv",
    index=False
)

comparison_df.to_csv(
    "Experiment_3_Model_Comparison.csv",
    index=False
)

category_df.to_csv(
    "Experiment_3_Category_Performance.csv",
    index=False
)

print("\nFiles saved successfully:")
print("1. Experiment_3_Final_Classification.csv")
print("2. Experiment_3_Model_Comparison.csv")
print("3. Experiment_3_Category_Performance.csv")