# -*- coding: utf-8 -*-
"""TSWMA-Experiment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woDRPIlwWtsL6dYl_MY-ExwrjS4vbatW
"""

# Install required libraries
!pip install nltk spacy scikit-learn pandas

# STEP 2: CREATE SENTIMENT DATASET

import pandas as pd

data = {
    "Review": [
        "This movie was absolutely amazing and enjoyable.",
        "Leonardo DiCaprio gave an excellent performance in this film.",
        "I loved the story and the acting was excellent.",
        "I watched this movie in Mumbai and really enjoyed it.",
        "The film was fantastic and the performances were brilliant.",
        "Tom Hanks was wonderful and made the movie very entertaining.",
        "The movie was boring and very disappointing.",
        "I hated the film because the story was terrible.",
        "The acting was poor and the movie was too long.",
        "This was a horrible and disappointing experience.",
        "The movie was dull and completely uninteresting.",
        "Netflix released this disappointing movie last year.",
        "The story was good and the characters were interesting.",
        "The movie had great visuals but the story was weak.",
        "Overall, I really enjoyed this entertaining movie."
    ],

    "Sentiment": [
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Positive",
        "Negative",
        "Positive"
    ]
}

df = pd.DataFrame(data)

print("Sentiment Dataset:")
display(df)

# STEP 3: WORD-LEVEL TOKENIZATION

import nltk
from nltk.tokenize import word_tokenize

# Download tokenizer data
nltk.download('punkt')
nltk.download('punkt_tab')

# Apply word-level tokenization
df["Tokens"] = df["Review"].apply(word_tokenize)

print("Tokenized Reviews:")
display(df[["Review", "Tokens"]])

# STEP 4: STOP-WORD REMOVAL

from nltk.corpus import stopwords

# Download English stop words
nltk.download('stopwords')

# Get standard English stop words
stop_words = set(stopwords.words('english'))

# Remove stop words
df["Filtered_Tokens"] = df["Tokens"].apply(
    lambda tokens: [
        word for word in tokens
        if word.lower() not in stop_words
    ]
)

print("Reviews After Stop-Word Removal:")
display(df[["Review", "Tokens", "Filtered_Tokens"]])

# STEP 5: STEMMING USING PORTER STEMMER

from nltk.stem import PorterStemmer

# Create Porter Stemmer
stemmer = PorterStemmer()

# Apply stemming to filtered tokens
df["Stemmed_Tokens"] = df["Filtered_Tokens"].apply(
    lambda tokens: [
        stemmer.stem(word)
        for word in tokens
    ]
)

print("Reviews After Stemming:")
display(df[["Review", "Filtered_Tokens", "Stemmed_Tokens"]])

# STEP 6: LEMMATIZATION USING WORDNET LEMMATIZER

from nltk.stem import WordNetLemmatizer

# Download WordNet data
nltk.download('wordnet')
nltk.download('omw-1.4')

# Create WordNet Lemmatizer
lemmatizer = WordNetLemmatizer()

# Apply lemmatization to filtered tokens
df["Lemmatized_Tokens"] = df["Filtered_Tokens"].apply(
    lambda tokens: [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]
)

print("Reviews After Lemmatization:")
display(df[["Review", "Filtered_Tokens", "Lemmatized_Tokens"]])

# STEP 7: COMPARISON OF STEMMING AND LEMMATIZATION

comparison = []

for original, stemmed, lemmatized in zip(
    df["Filtered_Tokens"],
    df["Stemmed_Tokens"],
    df["Lemmatized_Tokens"]
):
    for orig, stem, lemma in zip(original, stemmed, lemmatized):
        comparison.append((orig, stem, lemma))

comparison_df = pd.DataFrame(
    comparison,
    columns=["Original Word", "Stemmed Word", "Lemmatized Word"]
)

print("Stemming vs Lemmatization:")
display(comparison_df)

# STEP 8A: INSTALL AND LOAD SPACY ENGLISH MODEL

!python -m spacy download en_core_web_sm

# STEP 8B: NAMED ENTITY RECOGNITION (NER)

import spacy

# Load the English language model
nlp = spacy.load("en_core_web_sm")

# Function to extract named entities
def extract_entities(text):
    doc = nlp(text)
    return [(ent.text, ent.label_) for ent in doc.ents]

# Apply NER to the reviews
df["Named_Entities"] = df["Review"].apply(extract_entities)

print("Named Entity Recognition Results:")
display(df[["Review", "Named_Entities"]])

# STEP 9: GENERATE UNIGRAMS

from collections import Counter

# Combine all filtered tokens from the reviews
all_tokens = [
    word.lower()
    for tokens in df["Filtered_Tokens"]
    for word in tokens
    if word.isalpha()
]

# Count unigram frequencies
unigram_freq = Counter(all_tokens)

print("Top 15 Most Frequent Unigrams:")

for word, frequency in unigram_freq.most_common(15):
    print(f"{word}: {frequency}")

# STEP 10: GENERATE BIGRAMS

from nltk.util import bigrams

# Generate bigrams from all filtered tokens
bigram_list = list(bigrams(all_tokens))

# Count bigram frequencies
bigram_freq = Counter(bigram_list)

print("Top 15 Most Frequent Bigrams:")

for bigram, frequency in bigram_freq.most_common(15):
    print(f"{' '.join(bigram)}: {frequency}")

# STEP 11: GENERATE TRIGRAMS

from nltk.util import trigrams

# Generate trigrams from all filtered tokens
trigram_list = list(trigrams(all_tokens))

# Count trigram frequencies
trigram_freq = Counter(trigram_list)

print("Top 15 Most Frequent Trigrams:")

for trigram, frequency in trigram_freq.most_common(15):
    print(f"{' '.join(trigram)}: {frequency}")

# STEP 12: COMPARE N-GRAM FREQUENCIES

# Get the top 5 frequencies for each type
unigram_top = unigram_freq.most_common(5)
bigram_top = bigram_freq.most_common(5)
trigram_top = trigram_freq.most_common(5)

# Create comparison table
ngram_comparison = pd.DataFrame({
    "Unigrams": [f"{word}: {freq}" for word, freq in unigram_top],
    "Bigrams": [f"{' '.join(word)}: {freq}" for word, freq in bigram_top],
    "Trigrams": [f"{' '.join(word)}: {freq}" for word, freq in trigram_top]
})

print("Top 5 N-Gram Frequency Comparison:")
display(ngram_comparison)

# STEP 13: COUNT VECTORIZATION

from sklearn.feature_extraction.text import CountVectorizer

# Create CountVectorizer
count_vectorizer = CountVectorizer()

# Convert reviews into numerical form
count_matrix = count_vectorizer.fit_transform(df["Review"])

# Get feature names
count_features = count_vectorizer.get_feature_names_out()

# Convert to DataFrame for easy viewing
count_df = pd.DataFrame(
    count_matrix.toarray(),
    columns=count_features
)

print("CountVectorizer - Document-Term Matrix:")
display(count_df)

# STEP 14: TF-IDF VECTORIZATION

from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Convert reviews into TF-IDF numerical representation
tfidf_matrix = tfidf_vectorizer.fit_transform(df["Review"])

# Get feature names
tfidf_features = tfidf_vectorizer.get_feature_names_out()

# Convert to DataFrame for easy viewing
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_features
)

print("TF-IDF - Document-Term Matrix:")
display(tfidf_df)

# STEP 15: VISUALIZE MOST FREQUENT TERMS

import matplotlib.pyplot as plt

# Select the 10 most frequent words
top_words = unigram_freq.most_common(10)

words = [word for word, frequency in top_words]
frequencies = [frequency for word, frequency in top_words]

# Create bar chart
plt.figure(figsize=(10, 5))
plt.bar(words, frequencies)

plt.title("Top 10 Most Frequent Terms")
plt.xlabel("Terms")
plt.ylabel("Frequency")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# STEP 16: NAÏVE BAYES SENTIMENT CLASSIFIER

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, f1_score, classification_report

# Features (TF-IDF) and target labels
X = tfidf_matrix
y = df["Sentiment"]

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

# Train the Naïve Bayes model
model = MultinomialNB()
model.fit(X_train, y_train)

# Predict sentiments
y_pred = model.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, pos_label="Positive")

print("NAÏVE BAYES MODEL RESULTS")
print("-" * 35)
print(f"Accuracy : {accuracy:.2f}")
print(f"F1 Score : {f1:.2f}\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))

# STEP 17: CREATE CLEANED TEXT

# Create cleaned text using lemmatized tokens
df["Cleaned_Text"] = df["Lemmatized_Tokens"].apply(
    lambda tokens: " ".join(
        word.lower()
        for word in tokens
        if word.isalpha()
    )
)

print("Cleaned Text:")
display(df[["Review", "Cleaned_Text"]])

# STEP 18: CREATE FINAL CSV

# Create n-gram text representations for each review
df["Unigrams"] = df["Filtered_Tokens"].apply(
    lambda tokens: " ".join(
        word.lower() for word in tokens if word.isalpha()
    )
)

df["Bigrams"] = df["Filtered_Tokens"].apply(
    lambda tokens: " | ".join(
        " ".join(pair)
        for pair in bigrams(
            [word.lower() for word in tokens if word.isalpha()]
        )
    )
)

df["Trigrams"] = df["Filtered_Tokens"].apply(
    lambda tokens: " | ".join(
        " ".join(triple)
        for triple in trigrams(
            [word.lower() for word in tokens if word.isalpha()]
        )
    )
)

# Select the important columns for the final CSV
final_df = df[
    [
        "Review",
        "Sentiment",
        "Cleaned_Text",
        "Unigrams",
        "Bigrams",
        "Trigrams",
        "Named_Entities"
    ]
].copy()

# Save the final CSV
final_df.to_csv(
    "experiment1_final_output.csv",
    index=False
)

print("Final CSV created successfully!")
print("File name: experiment1_final_output.csv")

display(final_df)

# STEP 19: FINAL CSV WITH VECTORIZED REPRESENTATIONS

# Add CountVectorizer representation for each review
final_df["CountVectorizer"] = [
    " ".join(map(str, row))
    for row in count_matrix.toarray()
]

# Add TF-IDF representation for each review
final_df["TF_IDF"] = [
    " ".join(f"{value:.4f}" for value in row)
    for row in tfidf_matrix.toarray()
]

# Save the complete final CSV
final_df.to_csv(
    "Experiment_1_Final_Output.csv",
    index=False
)

print("Final CSV created successfully!")
print("File name: Experiment_1_Final_Output.csv")

print("\nFinal CSV Columns:")
print(final_df.columns.tolist())

display(final_df)